use_frameworks!

platform :ios, '9.0'

target 'JWXToast_Example' do
  pod 'JWXToast', :path => '../'

  target 'JWXToast_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
